---
development:
  cloud_name: ikeshavgiri
  api_key: '648546525971327'
  api_secret: cOlhlN76axVkXTWSA-eGZYZGtdM
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: ikeshavgiri
  api_key: '648546525971327'
  api_secret: cOlhlN76axVkXTWSA-eGZYZGtdM
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: ikeshavgiri
  api_key: '648546525971327'
  api_secret: cOlhlN76axVkXTWSA-eGZYZGtdM
  enhance_image_tag: true
  static_image_support: false
